cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

This keeps the snapshots tree in the state if was in the beginning, except for the newly-created snapshot.

Remove the backing snapshot after reverting. Made snapshot removal more robust.

---

cinder/volume/drivers/vmware/vmdk.py

Change in the implementation of snapshot of attached volume in VMware Cinder driver addressing the 'already a snapshot' issue with VVol.

Do not snapshot the attachment VM but keep the full clone

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_volumeops.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

Until now, when creating a snapshot from an attached volume, only the
additional unwanted disks got remove and the NICs/VIFs were kept. With
nsx-t this is a problem, as it does not allow duplicate MAC addresses
on the same logical switch. Therefore, we now remove all VIFs - or
rather every device that has a "macAddress" attribute - in the
clone-process.

[vmware] Remove all NICs from snapshot

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

This is addressing the fix for restoring VVol volumes from swift
backup. cinder-backup needs to upload the backup data to VMWare
via HttpNfc API by performing a ImportVApp call. Since this
operation is about to replace the existing backing, we want to
keep the main logic in cinder-volume. Thus, we instruct
cinder-backup how to build the spec for ImportVApp via a json-like
syntax, since it seems that suds objects can't pe pickled or
simply can't be sent plain over RPC.

[vmware] Backup: send data needed to build an ImportVApp spec

---

cinder/volume/drivers/vmware/vmdk.py

This patch adds the capability reporting for
thin provisioning support as well as max over subscription
and reserve percentage.
https://docs.openstack.org/cinder/queens/admin/blockstorage-over-subscription.html

SAP: add reporting of thin provisioning

---

custom-requirements.txt

This patch adds redis to the custom-requirements.txt which is
needed by osprofiler

SAP: need redis for osprofiler

---

cinder/backup/chunkeddriver.py
cinder/tests/unit/backup/drivers/test_backup_handle.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/volumeops.py

Removes the need of `seek()` for every chunk that is being restored.
Instead, all the chunks are merged into a single sequence which is eventually written in a row.
It improves the write operation and allows connectors which don't support `seek()` (for now the vmdk connector) to support restoring of incremental backups.

Chunkeddriver - no seek

---

concourse_unit_test_task

This patch adds the concourse_unit_test_task file so we can run
unit tests during the loci image build process.

SAP: add concourse_unit_test_task

---

concourse_unit_test_task

There is a bug in setuptools that prevents python installs
from working correctly and you end up with an error
"error: 'egg_base' must be a directory name (got `src`)"
This patch upgrades the version of pip for running unit tests,
which should fix the error.

SAP: upgrade pip for concourse_unit_test_task

---

cinder/volume/drivers/vmware/vmdk.py

This patch fixes an issue that tempest found during
test_volume_snapshot_backup and the volume['migration_status'] was None
and can't be dereferenced as a string.

SAP: Fix when migration status is None

---

cinder/volume/drivers/vmware/vmdk.py

This patch ensures that the connector is not None during
force detach.  This issue was found during a tempest run.

SAP: fix force detach when connector is None

---

cinder/tests/unit/test_volume_types.py
cinder/tests/unit/volume/test_volume.py
cinder/tests/unit/volume/test_volume_retype.py
cinder/volume/api.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/volume_types.py
releasenotes/notes/min-max-vol-size-on-type-bc7c75ea73a74d02.yaml

Allows support for setting a minimum and/or maximum vol size that
can be created in extra_specs for each volume_type. This allows
setting size restrictions on different "tiers" of storage.
If configured, the size restrictions will be checked at the API level
as part of volume creation or retype.
2 new volume type keys are supported for setting the minimum volume
size and maximum volume size for that type.
'provisioning:min_vol_size'
'provisioning:max_vol_size'
Implements: blueprint min-max-vol-size-by-vol-type
This patch cherry-picked from master and conflicts resolved to merge into queens-m3
https://review.opendev.org/#/c/713710/
Change-Id: I222e778902a41e552e812896d7afd0516ee7fe68

SAP: Adds support for min/max volume size on vol_type

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

This patch adds some driver startup validation for the cinder.conf
vmware_storage_profile setting.   It makes sure the storage profile
exists.
This patch also adds some validation to the get_volume_stats, to make
sure not to try and call vcenter when we didn't find any datastores
during get_volume_stats() time.   We simply log a warning and move on.

[SAP] Added validation for vmware_storage_profile

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

This patch fixes the unit tests from the validate_storage_profiles
patch

[SAP] fix unit tests from last patch

---

cinder/backup/chunkeddriver.py
cinder/tests/unit/backup/drivers/test_backup_handle.py

* Fix a bug which was causing object readers to be kept in memory 
* Use `del` to delete object readers from the internal map, as we shouldn't wait for the garbage collector to remove them from the memory.
This should help decreasing the memory consumption while restoring backups.

Improve the deletion of object readers in BackupRestoreHandle

---

tox.ini

It failed to install the dependencies even with a pinned setuptools<45
in the upper constraints:
File "/tmp/pip-install-jx7q3ls5/MarkupSafe/setup.py", line 6, in <module>
from setuptools import setup, Extension, Feature
ImportError: cannot import name 'Feature'
The problem is, that a newer versions of `virtualenv` also pull in a new
version of setuptools. I haven't found a way to constrain the setuptools
version used by tox's creation of a virtualenv. Therefore, we now limit
the virtualenv version, which should bring us back to supported
territory.

SAP: Make tox -e pep8 work again

---

cinder/scheduler/manager.py
cinder/tests/unit/scheduler/test_scheduler.py

This fixes the bug of manager trying to access .obj of a PoolState,
instead it should access the PoolState properties directly, because
that's what the scheduler driver returns.

fix - scheduler manager find_backend_for_connector return value

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

This includes several fixes to make both host migrations and driver
migrations work.
* It allows to migrate_volume for 'reserved' volumes as well, so that
a volume can be migrated by the driver before it is attached
* It fixes the host migration (with force_host_copy enabled) by
implementing update_migrated_volume which updates the backing uuids.
Also fixes the terminate_connection to match the condition from the
initialize_connection for renaming and updating the backing after a
migration or a backup restore.
* It fixes a development artifact which was causing the RPC endpoints of
the VMDK driver to not be advertised (it was appending to the
additional_endpoints instead of extending the list).

FIX vmware migrations issues

---

cinder/tests/unit/volume/test_volume_retype.py
cinder/volume/api.py

Cinder wasn't honoring AZ when doing a retype as described in the
upstream bug here:
https://bugs.launchpad.net/cinder/+bug/1883928
This patch ensures that the AZ is placed inside the request spec
such that the AvailabilityZoneFilter can see it and use it when
determining the host for the new volume.

[SAP] Fix retype with AZ

---

custom-requirements.txt

This patch adds jaeger-client to the custom-requirements.txt,
which is required when osprofiler uses jaeger as backend.

SAP: need jaeger-client for osprofiler

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/vmdk.py

This patch adds a new config option that allows for randomizing
the selection of datastores at backing creation time.  First the
best datastores are chosen, which are the most connected datatstores
with the most space available.  Then that list of datastores is
randomized for selection.  The first datastore in that random list is
chosen.  This helps the driver not always pick the same datastore
when each datastore reports lots of free space.

[SAP] Randomize the selection of best datastores

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py

This patch updates one of the unit tests that fails py3 due to a
change in our version of the vmdk driver.

[SAP] Fix py3 unit tests

---

concourse_unit_test_task

This patch updates the running of the concourse unit test task
against train to include the libpq-dev package as well as make
sure we run py3 tox.

[SAP] Add libpq-dev to concourse_unit_test_task

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/vmdk.py

This patch adds a new config option that allows for randomizing
the selection of datastores at backing creation time.  First the
best datastores are chosen, which are the most connected datatstores
with the most space available.  Then that list of datastores is
randomized for selection.  The first datastore in that random list is
chosen.  This helps the driver not always pick the same datastore
when each datastore reports lots of free space.
Change-Id: I3992fa1a0cb5f059140685c74f70f8047bbb1480

Randomize the selection of best datastores

---

concourse_unit_test_task

Update the concourse_unit_test_task to remove the py27 tests
as train will run on py3.

[SAP] No need for py27 tests in train

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

This patch passes in the randomization settings to the datastore
selector object during driver do_setup() time.  Previously
those values were passed ony if the ds object didn't already exist.

[SAP] fix randomize datastore selection

---

cinder/volume/drivers/vmware/vmdk.py

In the migration from queens to train there was a missing call
to initialize the volumeops object correctly with the session.
This patch addresses that issue and updates the ds_sel and volumeops
property methods with the train codebase upstream.

Fix do_setup issues related to missing session.

---

cinder/volume/drivers/vmware/vmdk.py

This patch fixes a problem when creating a volume from snapshot
when the size of the volume is larger than the original snapshot.
The problem was caused by python creating a float value from the
size calculation, and the vmware api not being able to process the
size float.  The value needs to be a whole number/int.

Fix create from snapshot with larger size

---

cinder/volume/drivers/vmware/vmdk.py

This patch fixes a queens -> train driver issue.
The additional_endpoints needs to be extended, not appended.

[SAP] fix driver init of additional_endpoints

---

concourse_unit_test_task

When I ran this locally on 18.04 all the tests pass.  If pip gets
upgraded, then it can't resolve conflicts.

[SAP] Don't upgrade pip to run unit tests

---

concourse_unit_test_task

This patch adds back tox to the CI unit test.

[SAP] Ensure tox is installed for CI unit tests

---

test-requirements.txt

This patch downgrades the pycodestyle from 2.6.0, which caused
a conflict with flake8.

[SAP] downgrade the pycodestyle

---

tools/check_exec.py

This check regularly fails and is pretty much useless for our needs
of checking documentation and release notes for executables.

SAP update tools/check_exec.py to work

---

cinder/backup/chunkeddriver.py
cinder/backup/manager.py
cinder/backup/rpcapi.py
cinder/volume/manager.py
cinder/volume/rpcapi.py

This patch updates the backup process to call the volume manager
asynchronously to get the backup device in which to do the backup on.
This fixes a major issue with certain cinder drivers that take a long
time to create a temporary clone of the volume being backed up.

Rework backup process to make it async

---

cinder/volume/flows/manager/create_volume.py

This patch fixes an issue with calling create volume from backup.
There are 2 ways to create a volume from a backup.
1) calling cinder backup-restore
2) calling cinder create --backup-id
There is a series of issues with using #2 with vmware due to:
A) the volume is put into 'creating' status before calling the
backup manager to restore the bits to the new raw volume.
B) the vmware driver uses the volume status field to determine if
it should add required information to be returned in
initialize_connection() to exist for os-brick to return a
VmdkWriteHandle vs a VmdkReadHandle.
Both A and B combined results in 100% failure rate for creating a
volume from back up using technique #2.
Changing the volume status to restoring after the raw cinder volume
has been created fixes this issue.

[SAP] Force volume create from backup to restoring

---

cinder/tests/unit/volume/drivers/vmware/test_remote.py
cinder/volume/drivers/vmware/remote.py
cinder/volume/drivers/vmware/vmdk.py

The actual live-migration is happening in nova
But nova needs to know, where to place the volume.
An empty backing vm will be created, and nova takes care of the rest

Vmware: Create empty backing for live-migration

---

cinder/volume/api.py

The new workflow for migrating volumes is to create
an attachment with connection info.
We need to migrate the volume the same way as with the old
initialize_connection call to make it work there

[SAP] Also migrate on attachment creation

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_volumeops.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

`WithRetrieval` ensures, that `cancel_retrieval` is called also when there is an exception.
If that isn't done, the VSphere server is leaking resources.
It also fixes `VMwareVolumeOps.get_hosts` when there are more than `vmware_max_objects_retrieval`
hosts. The function does neither call `continue_`- nor `cancel_retrieval`.
So, if there are more hosts, you will only get the first `vmware_max_objects_retrieval`,
and on top of it, leak a view on vserver side.

VmWare: Use WithRetrieval instead of own continue_/cancel_retrieval

---

cinder/tests/unit/volume/drivers/vmware/test_remote.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_volumeops.py
cinder/volume/drivers/vmware/remote.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

If we have a cinder volume type resulting in a disk with storage IO profile,
then we also need to specify the target vcenter uuid of the storage profile in
the disk-locator.
Specifying it on the VM as profile is not enough, it will raise an unsupported
operation error (as does not specifying it at all)

VmWare: Relocate with Storage IO Profile

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_datastore.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/volumeops.py

This patch filters out hosts in a cluster that has been
marked by ops as 'buildup'.  This ensures that we don't use
hosts that aren't ready to be used quite yet.
Ops has to set a 'buildup' : 'true' custom attribute in the
cluster.  This patch will reverse lookup which cluster a host is in
and ensure that the cluster isn't marked as buildup.

[SAP] Filter out hosts that are marked buildup

---

cinder/tests/unit/volume/drivers/vmware/test_fcd.py
cinder/tests/unit/volume/drivers/vmware/test_remote.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_datastore.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/tests/unit/volume/test_capabilities.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/remote.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/manager.py

This adds the ability to expose datastores as pools.  This patchset also supports enabling and disabling pools.  The host entries for all backing created volumes will get updated when pools is enabled or disabled.
TODO:
I will rebase this set into a single commit prior to merging.
In order to support switching from non-pools to pools seamlessly, I had to find a mechanism to automatically the host entries for every volume to include the correct datastore that the backing lives on.   Not all volumes have a backing, since our deployment includes the setting for lazy backing creation.  This means a volume's backing isn't created at create_volume() time, but during any portion of the volume's lifecycle needs to write data to it (clone, create image from volume, attach, etc.)
Major …

Vmware datastores as pools

---

lower-constraints.txt
requirements.txt

The suds-jurko requirement was needed by the Disco and Datacore drivers,
but of which have since been removed. This cleans up the requirements to
remove that library.
Change-Id: I141c2c141aeea84272d2b04610e53822bc3b3371
Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>
Cherry picked from upstream 50756ce5de9748277434a171c11a2f2a4901364e

[SAP] Remove suds from requirements

---

lower-constraints.txt
requirements.txt

This patch removes suds-jurko from requirements.
oslo.vmware has been changed to use suds-community

[SAP] Remove suds-jurko from requirements.

---

cinder/volume/drivers/vmware/vmdk.py

This patch fixes an issue with reporting the connection capabilities
in pools enabled stats for vmdk driver.

[SAP] Update connection_capabilities reporting in stats

---

cinder/api/contrib/vmware_migrate.py
cinder/api/contrib/volume_actions.py
cinder/api/schemas/vmware_extension_actions.py
cinder/api/v3/attachments.py
cinder/opts.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/tests/unit/volume/test_volume.py
cinder/volume/api.py
cinder/volume/drivers/vmware/vmdk.py

This is a POC/WIP to add the extension to the cinder API
to allow calling os-migrate_volume_by_connector.  This will
still be an admin API endpoint as it will call migrate_volume
underneath it.
Notes:
I tested this on my home devstack and was able to manually issue the call 
to migrate via connector.   It worked. :)
For using this manually you can do this:
```
connector = {"connection_capabilities": ["vmware_service_instance_uuid:......"]}
body = {"connector": connector}
client.volumes._action('os-migrate_volume_by_connector', volume, body)
```

[SAP] Add vmware extension for migration

---

cinder/scheduler/filters/shard_filter.py
cinder/tests/unit/scheduler/test_shard_filter.py

When we try to find a backend for a connector, we got called by an admin
to migrate a volume towards a connector - a specific vCenter housing a
specific VM. In those cases, we don't want to prohibit the migration
just because the volume's project doesn't have the appropriate shards
set, as the shards should more steer where we put volumes initially, not
prohibit the user from attaching a volume if it's necessary on a "stray"
instance.
Change-Id: Iccf5f5287eda536adafe925c76054f14827c467e
---
For reference: [This decorator](https://github.com/sapcc/cinder/blob/3f9e139e8077a11168e82fa97f7c773c8e55b6a3/cinder/scheduler/manager.py#L358) sets the `operation` key in the RequestSpec. There's another example using this in [the CapabilitiesFilter](https://github.com/sapcc/cinder/blob/3f9e139e8077a11 …

[SAP] ShardFilter passes everything for find_backend_for_connector

---

cinder/volume/drivers/vmware/vmdk.py

This tracing was useful during development of the datastores
as pool, now it's just noise.

[SAP] Remove the tracing from _get_datastores_for_profiles

---

cinder/scheduler/filters/sap_large_volume_filter.py
setup.cfg

This filter disallows any volumes larger than 2TB to be created on
any datastore that has 'vvol' in it's name.

[SAP] add SAPLargeVolumeFilter

---

cinder/tests/unit/volume/drivers/vmware/test_remote.py
cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/api.py
cinder/volume/drivers/vmware/remote.py
cinder/volume/drivers/vmware/vmdk.py

The fix consists of two changes, each in their commit.
- We lock now the volumes before migrating them, so we have to handle the changed status
- We parse the current volume (cinder-)host to determine the datastore, which needs to be overridden with the target cinder-host.

Fix live migration

---

cinder/volume/api.py

If there is an exception raised in attachment_update,
the created attachment db record may persist,
unless we delete it

Delete attachment on exception in create

---

cinder/scheduler/filters/sap_large_volume_filter.py

The filter was getting a KeyError during snapshot_create
requests.
This patch reworks the filter to use the safety like the capacity
filter uses for getting the size out of the request spec.

[SAP] Fix an issue with SAPLargeVolumeFilter

---

cinder/volume/drivers/vmware/vmdk.py

This patch forces the pool stats to say they support
thick provisioning.

[SAP] Ensure pools specify thick_provisioning_support enabled

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

The Nova vmwareapi driver falls back to the extraConfig
option value nvp.vm-uuid to identify vms, if it cannot
find VMs by the config.instanceUuid attribue.
A clone copies the attribute, so when nova retries
to delete a vm after initially succeeding,
it will find the backing with the same value instead
and delete it instead.

Vmware: Remove nvp.vm-uuid extraConfig

---

cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

This patch tries to read any custom attributes associated with
each datastore and shove those attributes in the pool stats.
This will allow us to filter by custom attributes.
The end goal is to add a netapp backend fqdn custom attribute
so we know where each datastore lives.  This will allow cinder
to have affinity/anti-affinity to netapps.

[SAP] Add any custom attributes to pool stats

---

cinder/tests/unit/volume/test_manage_volume.py
cinder/volume/manager.py

This patch mirrors an upstream effort to fix issues related
to not tracking the allocated_capacity_gb volume stats entry
for backends.  This value is critical for the cinder scheduler
in determining capacity for provisioning requests per backend/pool.
This patch fixes:
migrate_volume
delete_group
revert_to_snapshot_generic

[SAP] Fixes to better account for allocated_capacity_gb

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

oslo.vmware has a new option to pass the Swift direct_url of an
image to VMware for being downloaded directly from there, instead
of cinder-volume proxying between glance and VMware.
We can feature-toggle this on/off by controlling
`allow_pulling_images_from_url`
Depends on https://github.com/sapcc/oslo.vmware/pull/24

[vmware] Allow pulling images from Swift

---

cinder/volume/api.py

This patch adds the volume create time scheduler hint to the
volume metadata and uses that metadata at volume_migrate time.
This ensures that when a volume is migrated via normal cinder migrate
call, that the affinity/anti-affinity is still honored.

[SAP] ensure affinity/antiaffinity is maintained at migration time

---

cinder/volume/manager.py

We are still seeing negative values for allocated_capacity_gb in production.
This is a stop gap to not allow the values to go negative and then also log a
warning for it.
This patch looks for updates to allocated_capacity_gb going
negative and logs them along w/ the resource and then resets
the value to 0.
The hope is that seeing these warnings in logs will help find out
why they are happening to begin with.

[SAP] Trap negative values for allocated_capacity_gb

---

cinder/volume/api.py

This fixes a problem of storing the volume uuids in the metadata
{'scheduler_hint_same_host':
'f,0,5,1,d,d,d,3,-,b,2,b,4,-,4,5,2,2,-,b,0,8,7,-,6,4,c,d,8,f,a,5,c,7,a,3'}

[SAP] fix the metadata for affinity/anti-affinity

---

cinder/scheduler/manager.py
cinder/scheduler/rpcapi.py
cinder/tests/unit/scheduler/test_scheduler.py
cinder/volume/api.py
cinder/volume/manager.py
cinder/volume/rpcapi.py

This patch puts a fix in for the scheduler's copy of the
backend/pool's allocated_capacity_gb while doing a migrate
by connected.
This patch also reorders the RPC call to update the
allocated_capacity_gb inside the volume manager's migrate_volume call.
This will ensure:
1) The scheduler's copy of allocated_capacity_gb for a backend/pool is
updated for a migrate_by_connector in between the volume manager's
get_volume_stats() calls.
2) after the volume manager calls get_volume_stats on a driver the
allocated_capacity_gb has been updated from the last migration.
These issues were discovered by an overprovisioning of a few datastores
in eu-de-2, when a customer created 10+ volumes quickly and attached all
of them to a VM.  The volumes were all created on 1 shard, and then due
to the attach …

[SAP] Fix for allocated_capacity_gb not being updated

---

cinder/backup/manager.py
cinder/cmd/backup.py
cinder/opts.py
cinder/tests/unit/backup/test_backup.py
cinder/tests/unit/test_cmd.py
cinder/tests/unit/test_utils.py
cinder/utils.py
doc/source/admin/blockstorage-volume-backups.rst
releasenotes/notes/backup_max_operations-27753c748ba1dc1a.yaml

This is a backport from upstream master:
30c2289c9b0456d3783f01e3d65985ed1b09976a
https://github.com/openstack/cinder/commit/30c2289c9b0456d3783f01e3d65985ed1b09976a
This patch adds the backup_max_operations configuration option that
limits the number of concurrent backup and restore operations.
These operations can consume large amounts of RAM, so we should limit
them according to our system resources to avoid processes being killed
because we run out of memory.
The default is 15 concurrent operations, which could use up to 85GB
of RAM(in case of ceph which uses the maximum memory for this operation).
More details are added in the document.
Closes-Bug: #1865011
Co-authored-by: Rajat Dhasmana <rajatdhasmana@gmail.com>

[SAP] Backup: Limit number of concurent operations

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/datastore.py
cinder/volume/drivers/vmware/vmdk.py

This patch adds the ability to track if a datastore is available
to be used in get_volume_stats.  If a datastore is in maintenance
mode, then it can't accept volume provisioning requests.  So the
driver now marks the datastore/pool as 'down'.  When the datastore
comes back out of maintenance mode, then the pool_state is changed to
'up'.
Currently, Cinder doesn't have a built in mechanism for dealing with a
pool_state being down, but we can simulate it by adding an extra spec
setting in all volume types of pool_state='up'.  That way the
capability filter will filter out all pools that don't have that
capability coming from the driver.
This patch also changes where the backend_state is set so that
the scheduler can mark the service as down correctly.

[SAP] Added pool_state tracking. Updated backend_state

---

cinder/volume/manager.py
cinder/volume/rpcapi.py

This patch fixes a problem updated the allocated_capacity_gb
for the destination cinder host during volume migration.
We recently made a change to when we update the allocated_capacity_gb
during volume migration, which allowed an over allocation.  The
remove rpc call to update the destination host was moved to before
the call to migrate the volume to ensure that the scheduler had updated
stats for the destination, since the migration can take a long time.
The problem with this move is that the volume host entry wasn't updated
at the time of the call to update the remote destination host.  The
update was being called on the source host, so there was effectively
no change since the src and destination host was the same during both
calls to update_allocated_capacity_gb.  This patch fixes …

[SAP] update the new remote host allocated_capacity_gb

---

cinder/volume/api.py

This patch adds an additional check in the volume api
to ensure that cinder doesn't allow attached volumes
to be migrated to a different host.

[SAP] prevent cross host/shard migration

---

cinder/scheduler/manager.py
cinder/tests/unit/scheduler/test_scheduler.py
cinder/tests/unit/volume/test_rpcapi.py
cinder/tests/unit/volume/test_volume_migration.py
cinder/volume/api.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/manager.py
cinder/volume/rpcapi.py
cinder/volume/volume_utils.py

If the new size of a volume isn't accepted by the host
it will be rescheduled and migrated to another one.
Volumes that are in a group cannot be rescheduled because
migration to another host is not possible in that case.

Migrate the volume if resize can't happen on current host

---

cinder/volume/drivers/vmware/volumeops.py

This patch fixes a misspelled name of a vmware exception
from
StorageMigratonFailed to
StorageMigrationFailed

[SAP] Fix misnamed StorageMigrationFailed call

---

cinder/api/contrib/services.py
cinder/api/schemas/services.py
cinder/policies/services.py
cinder/tests/unit/volume/test_volume.py
cinder/volume/api.py
cinder/volume/manager.py
cinder/volume/rpcapi.py

This patch adds a custom API to force
the volume manager to recount all of it's volumes.
This enables us to update the allocated capacity for a running
cinder service.
This patch has a shared lock with the _report_driver_status call as well
so if the recount_host_volumes is working, then the driver stats won't
get reported until it is complete.

[SAP] Add new recount_host_stats API

---

cinder/volume/drivers/vmware/vmdk.py

This patch defaults to disabling the ability to go through every single volume and ensure the pool is set correctly. This was initially needed in the transition from aggregate info to datastores as pools.  This is not really needed now. It will eventually get moved to a utility.
EU-DE-1 / VC-b-0 takes 5 minutes to go through 4500 volumes at startup and was causing liveliness probe to repeatedly kill the pod because the driver hadn't finished going through all volumes.

[SAP] Add ability to disable updating provider_info

---

cinder/tests/unit/volume/drivers/vmware/test_vmware_vmdk.py
cinder/volume/drivers/vmware/vmdk.py

This patch fixes the reporting of multiattach capability in the
vmdk driver.   Multiattach -> multiattach

[SAP] Fix multiattach reporting for vmdk

---

cinder/volume/manager.py
cinder/volume/rpcapi.py

This patch fixes a problem with the volume
rcpapi.update_migrate_volume_capacity()
It was always pulling the remote host to call from the volume.service_topic_queue, which is always the current host entry, not the new host that the volume is migrating to.  This is how we were getting overcommited against remote datastores during volume attachments inducing a migration to another vcenter.  The remote wasn't actually getting called to update it's allocated_capacity_gb.

[SAP] Fix rpc call to remote host to update host capacity

---

cinder/volume/manager.py

This patch ensures that when a new volume is create and if it has scheduler hints for affinity/anti-affinity for other volumes, that the volumes get affinity/anti-affinity for the newly created volumes.  This ensures affinity and anti-affinity are both ways for volumes.

SAP propagate scheduler hints for volumes

---

cinder/scheduler/filters/sap_pool_down_filter.py
cinder/scheduler/host_manager.py
cinder/volume/drivers/vmware/vmdk.py
cinder/volume/manager.py
setup.cfg

This patch will check the capacity factors of a pool and check it's virtual_free_capacity left every time the volume manager gets the volume stats from the backend.  If the virtual_free_capacity is <= 0 then the pool is overcommited and will be marked down.
The new SAPPoolDownFilter will check against this pool_state and if it's down, then filter the pool out of results for the scheduler.
This patch also updates the vmware driver to properly report the thin/thick capability depending on the volume type's provisioning:type setting.  This is used to determine the proper capacity factors for the provisioning type.

[SAP] Mark a pool as down if overcommited

---

cinder/volume/drivers/vmware/vmdk.py
cinder/volume/drivers/vmware/volumeops.py

This patch checks datastores to see if they have alerts.
If the alert is red, the datastore will be marked as down
and the down reason is provided.

[SAP] Mark datastore down if it has red alert

---

cinder/volume/manager.py

When the pool stats are pulled from the volume driver and the max oversubscription ratio isn't set yet, the max oversubscription ratio comes from the default config setting, which is a string.  Have to force that to a float when using it for calculations.

[SAP] fix default max_oversubscription_ratio to float

---

cinder/tests/unit/volume/test_volume.py
cinder/volume/manager.py

This patch adds the cinder host name to the lock for collecting volume-stats to ensure the lock is contextual only inside each host volume process.  This will prevent other hosts for waiting for the same lock when they don't need to.

[SAP] Add context to the volume-stats tooz lock
